#!/bin/bash
su - postgres -c "psql -c 'CREATE DATABASE \"terra-mystica\";'"
su - postgres -c "psql --dbname terra-mystica -f /terra-mystica/schema/schema.sql"
su - postgres -c "psql -c 'CREATE ROLE daemon WITH LOGIN;'"
perl -e "printf qq(insert into secret (secret, shared_iv) values ('%x%x'::bytea, '%x'::bytea);), map { rand 2**32 } 0..2" > /secretinit.sql 
su - postgres -c "psql --dbname terra-mystica -f /secretinit.sql"
rm -f /secretinit.sql
su - postgres -c "psql --dbname terra-mystica -c \"INSERT INTO map_variant (id, terrain) VALUES ('95a66999127893f5925a5f591d54f8bcb9a670e6', 'E brown x brown black yellow x gray green red blue yellow blue E red yellow x blue gray red x x x yellow brown black gray E green black x x x brown green yellow x x x x E yellow gray green yellow black x blue red brown x green blue green E x x brown x x red black green gray x brown black E green red x x green x x x brown blue x gray red E gray x yellow gray blue red green x red gray x black E black blue x black brown gray blue x yellow black x red blue E gray green x red yellow black yellow x blue brown x brown E'), ('be8f6ebf549404d015547152d5f2a1906ae8dd90', 'brown gray green blue brown red brown black red blue green red black E yellow x x yellow black x x yellow green x x yellow E x x black x gray x green x black x red x x E green blue yellow x x red blue x red x gray brown E black brown red blue yellow brown green yellow x x green black red E gray green x x black gray x x x brown gray yellow E x x x gray x red x green x yellow black blue brown E yellow blue brown x x x blue black x gray brown red E blue black gray blue red green yellow brown gray x blue green gray E');\""
su - postgres -c "psql --dbname terra-mystica -c 'GRANT INSERT, SELECT, UPDATE, DELETE ON email TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON to_validate TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON map_variant TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_player TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_active_time TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_role TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON blacklist TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_note TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON secret TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON chat_message TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON chat_read TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON player_ratings TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_events TO daemon; GRANT INSERT, SELECT, UPDATE, DELETE ON game_options TO daemon;GRANT INSERT, SELECT, UPDATE, DELETE ON player TO daemon;'"
